## Numpy

In [1]:
import numpy as np

In [22]:
a = np.random.rand(5,10)
print(a)
a[0].dtype

[[0.91745373 0.79112869 0.52165903 0.47341069 0.33352982 0.70625878
  0.9358579  0.71439558 0.89668018 0.27589944]
 [0.08561062 0.88267299 0.50578756 0.44356829 0.74559212 0.98615475
  0.08079098 0.57224999 0.40521003 0.44124905]
 [0.9801707  0.59022501 0.08384013 0.02209035 0.64591334 0.67198959
  0.67848255 0.50593208 0.0926757  0.76018176]
 [0.58858074 0.00628069 0.2687377  0.35094187 0.74243279 0.63583689
  0.18752684 0.67723088 0.29728466 0.90291602]
 [0.18324222 0.97087581 0.66223957 0.11627857 0.49089163 0.07256104
  0.68347132 0.60337079 0.98691235 0.54730869]]


dtype('float64')

In [23]:
b = np.random.rand(7,10)
print(b)
b[0].dtype

[[0.9493693  0.48480287 0.00829277 0.41614314 0.89637429 0.367823
  0.96425227 0.11365377 0.0603055  0.41686083]
 [0.53490932 0.18573876 0.79051911 0.64603204 0.90396315 0.81643111
  0.96368702 0.37561752 0.77132076 0.67789901]
 [0.18544293 0.08999528 0.31634765 0.43965746 0.12188784 0.01210284
  0.63134694 0.72955378 0.38233691 0.89413105]
 [0.04368164 0.81543669 0.90255152 0.01949378 0.41083347 0.1326204
  0.7363168  0.9938526  0.15622935 0.5181746 ]
 [0.10989274 0.85729749 0.10639056 0.84080014 0.3198395  0.8866443
  0.25125738 0.68378539 0.51201303 0.52848885]
 [0.33391241 0.2926112  0.37299141 0.30730784 0.09003223 0.97388282
  0.31563536 0.28395739 0.17068246 0.11186164]
 [0.34982928 0.46339611 0.59171168 0.62582861 0.0258935  0.38144792
  0.90268478 0.32644738 0.18180263 0.32746937]]


dtype('float64')

In [18]:
a = a.reshape(-1, 5)
print(a)

[[0.65383332 0.08261491 0.93493136 0.26817336 0.02657881]
 [0.12854386 0.23558723 0.20531799 0.41547892 0.5196847 ]
 [0.98462614 0.37262625 0.8543502  0.84229406 0.93683901]
 [0.08331359 0.40748671 0.42853827 0.60906237 0.50733631]
 [0.04709103 0.34456448 0.8260522  0.40296091 0.98562626]
 [0.4203239  0.09889393 0.36814906 0.9910247  0.22805791]
 [0.74568638 0.27029168 0.74871662 0.17284257 0.44503638]
 [0.64825235 0.70171884 0.05124554 0.01204432 0.16162487]
 [0.15449372 0.02070362 0.4740337  0.93683051 0.1402295 ]
 [0.5767487  0.03963008 0.08246916 0.07848519 0.07997948]]


In [20]:
b = b.reshape(-1, 5)
print(b)

[[0.93451844 0.84187277 0.54050437 0.30569414 0.05974045]
 [0.33613792 0.39234657 0.69697818 0.44316818 0.42092181]
 [0.85996673 0.6435786  0.74491286 0.246404   0.99918934]
 [0.2194271  0.27470138 0.89198506 0.45078262 0.45283813]
 [0.50118226 0.04912101 0.11438472 0.39193792 0.84444835]
 [0.33789337 0.25184949 0.29670121 0.37606446 0.44514342]
 [0.97715136 0.7607796  0.0548336  0.27345141 0.88525224]
 [0.03185965 0.70899815 0.61976699 0.92430538 0.97442072]
 [0.76142498 0.4817983  0.53451784 0.56082571 0.91564958]
 [0.44088101 0.3912321  0.30300152 0.01854988 0.62297212]
 [0.58120445 0.7702369  0.69046096 0.99685509 0.32974101]
 [0.47133428 0.02062341 0.88337005 0.77422301 0.19932271]
 [0.54041741 0.98232165 0.21297228 0.71646802 0.37601834]
 [0.03236641 0.3765324  0.20855271 0.36123143 0.42593013]]


In [21]:
c = np.concatenate((a,b),axis=0)
print(c)

[[0.65383332 0.08261491 0.93493136 0.26817336 0.02657881]
 [0.12854386 0.23558723 0.20531799 0.41547892 0.5196847 ]
 [0.98462614 0.37262625 0.8543502  0.84229406 0.93683901]
 [0.08331359 0.40748671 0.42853827 0.60906237 0.50733631]
 [0.04709103 0.34456448 0.8260522  0.40296091 0.98562626]
 [0.4203239  0.09889393 0.36814906 0.9910247  0.22805791]
 [0.74568638 0.27029168 0.74871662 0.17284257 0.44503638]
 [0.64825235 0.70171884 0.05124554 0.01204432 0.16162487]
 [0.15449372 0.02070362 0.4740337  0.93683051 0.1402295 ]
 [0.5767487  0.03963008 0.08246916 0.07848519 0.07997948]
 [0.93451844 0.84187277 0.54050437 0.30569414 0.05974045]
 [0.33613792 0.39234657 0.69697818 0.44316818 0.42092181]
 [0.85996673 0.6435786  0.74491286 0.246404   0.99918934]
 [0.2194271  0.27470138 0.89198506 0.45078262 0.45283813]
 [0.50118226 0.04912101 0.11438472 0.39193792 0.84444835]
 [0.33789337 0.25184949 0.29670121 0.37606446 0.44514342]
 [0.97715136 0.7607796  0.0548336  0.27345141 0.88525224]
 [0.03185965 0

In [25]:
print(c[:, [4, 2, 3, 0, 1]])

[[0.02657881 0.93493136 0.26817336 0.65383332 0.08261491]
 [0.5196847  0.20531799 0.41547892 0.12854386 0.23558723]
 [0.93683901 0.8543502  0.84229406 0.98462614 0.37262625]
 [0.50733631 0.42853827 0.60906237 0.08331359 0.40748671]
 [0.98562626 0.8260522  0.40296091 0.04709103 0.34456448]
 [0.22805791 0.36814906 0.9910247  0.4203239  0.09889393]
 [0.44503638 0.74871662 0.17284257 0.74568638 0.27029168]
 [0.16162487 0.05124554 0.01204432 0.64825235 0.70171884]
 [0.1402295  0.4740337  0.93683051 0.15449372 0.02070362]
 [0.07997948 0.08246916 0.07848519 0.5767487  0.03963008]
 [0.05974045 0.54050437 0.30569414 0.93451844 0.84187277]
 [0.42092181 0.69697818 0.44316818 0.33613792 0.39234657]
 [0.99918934 0.74491286 0.246404   0.85996673 0.6435786 ]
 [0.45283813 0.89198506 0.45078262 0.2194271  0.27470138]
 [0.84444835 0.11438472 0.39193792 0.50118226 0.04912101]
 [0.44514342 0.29670121 0.37606446 0.33789337 0.25184949]
 [0.88525224 0.0548336  0.27345141 0.97715136 0.7607796 ]
 [0.97442072 0

## Pandas

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('assults.csv')

In [33]:
data.info()
data.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 14 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   Index                                  2020 non-null   int64  
 1   Area_unit_2013_code                    2020 non-null   int64  
 2   Area_unit_2013_label                   2020 non-null   object 
 3   Victimisations_calendar_year_2015      2020 non-null   int64  
 4   Population_mid_point_2015              2020 non-null   int64  
 5   Rate_per_10000_population              1603 non-null   object 
 6   Rate_ratio_NZ_average_rate             1603 non-null   float64
 7   Urban_area_2013_code                   2020 non-null   int64  
 8   Urban_area_2013_label                  2020 non-null   object 
 9   Urban_area_type                        2020 non-null   object 
 10  Territorial_authority_area_2013_code   2020 non-null   int64  
 11  Terr

Index                                    2020
Area_unit_2013_code                      2020
Area_unit_2013_label                     2020
Victimisations_calendar_year_2015         106
Population_mid_point_2015                 586
Rate_per_10000_population                 237
Rate_ratio_NZ_average_rate                101
Urban_area_2013_code                      150
Urban_area_2013_label                     150
Urban_area_type                             4
Territorial_authority_area_2013_code       68
Territorial_authority_area_2013_label      68
Region_2013_code                           17
Region_2013_label                          17
dtype: int64

In [31]:
data.sort_values('Region_2013_label')

Index  Area_unit_2013_code     Area_unit_2013_label  \
1649   1650               625200  Oceanic-Chatham Islands   
1705   1706               666669           Bounty Islands   
1686   1687               614002         Kermadec Islands   
1615   1616               666670   Oceanic-Snares Islands   
1656   1657               666673        Antipodes Islands   
...     ...                  ...                      ...   
1488   1489               584405                 Orowaiti   
1789   1790               584936            Arnold Valley   
1785   1786               584408                Mokihinui   
978     979               585325                    Haast   
1406   1407               584934          Greymouth Rural   

      Victimisations_calendar_year_2015  Population_mid_point_2015  \
1649                                  0                          0   
1705                                  0                          0   
1686                                  0                          0   
1615                                  0                          0   
1656                                  0                          0   
...                                 ...                        ...   
1488                                  1                        710   
1789                                  0                        170   
1785                                  0                        150   
978                                   4                        260   
1406                                  1                         80   

     Rate_per_10000_population  Rate_ratio_NZ_average_rate  \
1649                       NaN                         NaN   
1705                       NaN                         NaN   
1686                       NaN                         NaN   
1615                       NaN                         NaN   
1656                       NaN                         NaN   
...                        ...                         ...   
1488                        14                         0.3   
1789                       NaN                         NaN   
1785                       NaN                         NaN   
978                        154                         2.9   
1406                       125                         2.4   

      Urban_area_2013_code                Urban_area_2013_label  \
1649                   511                              Oceanic   
1705                   502  Rural (Incl.some Off Shore Islands)   
1686                   502  Rural (Incl.some Off Shore Islands)   
1615                   511                              Oceanic   
1656                   502  Rural (Incl.some Off Shore Islands)   
...                    ...                                  ...   
1488                   502  Rural (Incl.some Off Shore Islands)   
1789                   502  Rural (Incl.some Off Shore Islands)   
1785                   502  Rural (Incl.some Off Shore Islands)   
978                    502  Rural (Incl.some Off Shore Islands)   
1406                   502  Rural (Incl.some Off Shore Islands)   

     Urban_area_type  Territorial_authority_area_2013_code  \
1649      Rural area                                    67   
1705      Rural area                                   999   
1686      Rural area                                   999   
1615      Rural area                                   999   
1656      Rural area                                   999   
...              ...                                   ...   
1488      Rural area                                    55   
1789      Rural area                                    56   
1785      Rural area                                    55   
978       Rural area                                    57   
1406      Rural area                                    56   

     Territorial_authority_area_2013_label  Region_2013_code  \
1649             Chatham Islands Territory                99   
1705    A

In [41]:
data.sort_values('Population_mid_point_2015', ascending=False)

Index  Area_unit_2013_code     Area_unit_2013_label  \
0         1               514102    Auckland Central West   
3         4               514103    Auckland Central East   
27       28               525910           Pukekohe North   
260     261               505805                    Orewa   
891     892               509100               Greenhithe   
...     ...                  ...                      ...   
1692   1693               625901  Inlet-Dunedin City Bays   
1693   1694               614601   Inlet-Rangaunu Harbour   
1694   1695               626000        Inlet-Port Oamaru   
1695   1696               614602      Inlet-Doubtless Bay   
1687   1688               625101     Inlet-Port Lyttelton   

      Victimisations_calendar_year_2015  Population_mid_point_2015  \
0                                   550                      15900   
3                                   375                      13250   
27                                   91                       9980   
260                                  24                       9170   
891                                   6                       9100   
...                                 ...                        ...   
1692                                  0                          0   
1693                                  0                          0   
1694                                  0                          0   
1695                                  0                          0   
1687                                  0                          0   

     Rate_per_10000_population  Rate_ratio_NZ_average_rate  \
0                          346                         6.6   
3                          283                         5.4   
27                          91                         1.7   
260                         26                         0.5   
891                          7                         0.1   
...                        ...                         ...   
1692                       NaN                         NaN   
1693                       NaN                         NaN   
1694                       NaN                         NaN   
1695                       NaN                         NaN   
1687                       NaN                         NaN   

      Urban_area_2013_code              Urban_area_2013_label  \
0                        4              Central Auckland Zone   
3                        4              Central Auckland Zone   
27                     101                           Pukekohe   
260                      2             Northern Auckland Zone   
891                      2             Northern Auckland Zone   
...                    ...                                ...   
1692                   507  Inlet-in TA but not in Urban Area   
1693                   507  Inlet-in TA but not in Urban Area   
1694                   507  Inlet-in TA but not in Urban Area   
1695                   506                    Inlet-not in TA   
1687                   507  Inlet-in TA but not in Urban Area   

           Urban_area_type  Territorial_authority_area_2013_code  \
0          Main urban area                                    76   
3          Main urban area                                    76   
27    Secondary urban area                                    76   
260        Main urban area                                    76   
891        Main urban area                                    76   
...                    ...                                   ...   
1692            Rural area                                    71   
1693            Rural area                                     1   
1694            Rural area                                    68   
1695            Rural area                                   999   
1687            Rural area                                    60   

     Territorial_authority_area_2013_label  Region_2013_code  \
0                        

In [42]:
data.sort_values('Victimisations_calendar_year_2015', ascending=False)

Index  Area_unit_2013_code             Area_unit_2013_label  \
0         1               514102            Auckland Central West   
1         2               573101  Willis Street-Cambridge Terrace   
2         3               529700                 Hamilton Central   
3         4               514103            Auckland Central East   
4         5               591500                 Cathedral Square   
...     ...                  ...                              ...   
1744   1745               614700          Inlet-Whangaroa Harbour   
1743   1744               617604            Tidal-Manukau Harbour   
1742   1743               622201            Inlet-Porirua Harbour   
1741   1742               549902                             Mara   
2019   2020               527007                    Horsham Downs   

      Victimisations_calendar_year_2015  Population_mid_point_2015  \
0                                   550                      15900   
1                                   447                       8300   
2                                   380                       3170   
3                                   375                      13250   
4                                   305                        570   
...                                 ...                        ...   
1744                                  0                         20   
1743                                  0                         20   
1742                                  0                         20   
1741                                  0                         10   
2019                                  0                       5440   

     Rate_per_10000_population  Rate_ratio_NZ_average_rate  \
0                          346                         6.6   
1                          539                        10.3   
2                        1,199                        22.9   
3                          283                         5.4   
4                        5,351                       102.3   
...                        ...                         ...   
1744                       NaN                         NaN   
1743                       NaN                         NaN   
1742                       NaN                         NaN   
1741                       NaN                         NaN   
2019                       NaN                         NaN   

      Urban_area_2013_code                Urban_area_2013_label  \
0                        4                Central Auckland Zone   
1                       20                      Wellington Zone   
2                        6                        Hamilton Zone   
3                        4                Central Auckland Zone   
4                       22                         Christchurch   
...                    ...                                  ...   
1744                   507    Inlet-in TA but not in Urban Area   
1743                   507    Inlet-in TA but not in Urban Area   
1742                   507    Inlet-in TA but not in Urban Area   
1741                   502  Rural (Incl.some Off Shore Islands)   
2019                     6                        Hamilton Zone   

      Urban_area_type  Territorial_authority_area_2013_code  \
0     Main urban area                                    76   
1     Main urban area                                    47   
2     Main urban area                                    16   
3     Main urban area                                    76   
4     Main urban area                                    60   
...               ...                                   ...   
1744       Rural area                                     1   
1743       Rural area                                    76   
1742       Rural area                                    44   
1741       Rural area                                    41   
2019  Main urban area                                    16   

     Territorial_authority_ar

In [45]:
data.sort_values('Victimisations_calendar_year_2015', ascending=False).head(10)['Area_unit_2013_label']

0              Auckland Central West
1    Willis Street-Cambridge Terrace
2                   Hamilton Central
3              Auckland Central East
4                   Cathedral Square
5               Auckland Harbourside
6                    Manukau Central
7           Palmerston North Central
8                             Kuirau
9                   Tauranga Central
Name: Area_unit_2013_label, dtype: object

In [46]:
data

Index  Area_unit_2013_code             Area_unit_2013_label  \
0         1               514102            Auckland Central West   
1         2               573101  Willis Street-Cambridge Terrace   
2         3               529700                 Hamilton Central   
3         4               514103            Auckland Central East   
4         5               591500                 Cathedral Square   
...     ...                  ...                              ...   
2015   2016               506653                        Riverhead   
2016   2017               610601                         Grasmere   
2017   2018               536513                   Bethlehem East   
2018   2019               574302                        Te Kainga   
2019   2020               527007                    Horsham Downs   

      Victimisations_calendar_year_2015  Population_mid_point_2015  \
0                                   550                      15900   
1                                   447                       8300   
2                                   380                       3170   
3                                   375                      13250   
4                                   305                        570   
...                                 ...                        ...   
2015                                  0                       3510   
2016                                  0                       3590   
2017                                  0                       3590   
2018                                  0                       4020   
2019                                  0                       5440   

     Rate_per_10000_population  Rate_ratio_NZ_average_rate  \
0                          346                         6.6   
1                          539                        10.3   
2                        1,199                        22.9   
3                          283                         5.4   
4                        5,351                       102.3   
...                        ...                         ...   
2015                       NaN                         NaN   
2016                       NaN                         NaN   
2017                       NaN                         NaN   
2018                       NaN                         NaN   
2019                       NaN                         NaN   

      Urban_area_2013_code                Urban_area_2013_label  \
0                        4                Central Auckland Zone   
1                       20                      Wellington Zone   
2                        6                        Hamilton Zone   
3                        4                Central Auckland Zone   
4                       22                         Christchurch   
...                    ...                                  ...   
2015                   502  Rural (Incl.some Off Shore Islands)   
2016                    24                         Invercargill   
2017                     9                             Tauranga   
2018                    20                      Wellington Zone   
2019                     6                        Hamilton Zone   

      Urban_area_type  Territorial_authority_area_2013_code  \
0     Main urban area                                    76   
1     Main urban area                                    47   
2     Main urban area                                    16   
3     Main urban area                                    76   
4     Main urban area                                    60   
...               ...                                   ...   
2015       Rural area                                    76   
2016  Main urban area                                    75   
2017  Main urban area                                    23   
2018  Main urban area                                    47   
2019  Main urban area                                    16   

     Territorial_authority_ar

In [55]:
data = data.drop(columns="Victimisations per population")
data

Index  Area_unit_2013_code             Area_unit_2013_label  \
0         1               514102            Auckland Central West   
1         2               573101  Willis Street-Cambridge Terrace   
2         3               529700                 Hamilton Central   
3         4               514103            Auckland Central East   
4         5               591500                 Cathedral Square   
...     ...                  ...                              ...   
2015   2016               506653                        Riverhead   
2016   2017               610601                         Grasmere   
2017   2018               536513                   Bethlehem East   
2018   2019               574302                        Te Kainga   
2019   2020               527007                    Horsham Downs   

      Victimisations_calendar_year_2015  Population_mid_point_2015  \
0                                   550                      15900   
1                                   447                       8300   
2                                   380                       3170   
3                                   375                      13250   
4                                   305                        570   
...                                 ...                        ...   
2015                                  0                       3510   
2016                                  0                       3590   
2017                                  0                       3590   
2018                                  0                       4020   
2019                                  0                       5440   

     Rate_per_10000_population  Rate_ratio_NZ_average_rate  \
0                          346                         6.6   
1                          539                        10.3   
2                        1,199                        22.9   
3                          283                         5.4   
4                        5,351                       102.3   
...                        ...                         ...   
2015                       NaN                         NaN   
2016                       NaN                         NaN   
2017                       NaN                         NaN   
2018                       NaN                         NaN   
2019                       NaN                         NaN   

      Urban_area_2013_code                Urban_area_2013_label  \
0                        4                Central Auckland Zone   
1                       20                      Wellington Zone   
2                        6                        Hamilton Zone   
3                        4                Central Auckland Zone   
4                       22                         Christchurch   
...                    ...                                  ...   
2015                   502  Rural (Incl.some Off Shore Islands)   
2016                    24                         Invercargill   
2017                     9                             Tauranga   
2018                    20                      Wellington Zone   
2019                     6                        Hamilton Zone   

      Urban_area_type  Territorial_authority_area_2013_code  \
0     Main urban area                                    76   
1     Main urban area                                    47   
2     Main urban area                                    16   
3     Main urban area                                    76   
4     Main urban area                                    60   
...               ...                                   ...   
2015       Rural area                                    76   
2016  Main urban area                                    75   
2017  Main urban area                                    23   
2018  Main urban area                                    47   
2019  Main urban area                                    16   

     Territorial_authority_ar

In [56]:
data.insert(5, "Victimisations per population", data['Victimisations_calendar_year_2015'] / data['Population_mid_point_2015'] * 100)

In [64]:
data

Index  Area_unit_2013_code             Area_unit_2013_label  \
0         1               514102            Auckland Central West   
1         2               573101  Willis Street-Cambridge Terrace   
2         3               529700                 Hamilton Central   
3         4               514103            Auckland Central East   
4         5               591500                 Cathedral Square   
...     ...                  ...                              ...   
2015   2016               506653                        Riverhead   
2016   2017               610601                         Grasmere   
2017   2018               536513                   Bethlehem East   
2018   2019               574302                        Te Kainga   
2019   2020               527007                    Horsham Downs   

      Victimisations_calendar_year_2015  Population_mid_point_2015  \
0                                   550                      15900   
1                                   447                       8300   
2                                   380                       3170   
3                                   375                      13250   
4                                   305                        570   
...                                 ...                        ...   
2015                                  0                       3510   
2016                                  0                       3590   
2017                                  0                       3590   
2018                                  0                       4020   
2019                                  0                       5440   

      Victimisations per population Rate_per_10000_population  \
0                          3.459119                       346   
1                          5.385542                       539   
2                         11.987382                     1,199   
3                          2.830189                       283   
4                         53.508772                     5,351   
...                             ...                       ...   
2015                       0.000000                       NaN   
2016                       0.000000                       NaN   
2017                       0.000000                       NaN   
2018                       0.000000                       NaN   
2019                       0.000000                       NaN   

      Rate_ratio_NZ_average_rate  Urban_area_2013_code  \
0                            6.6                     4   
1                           10.3                    20   
2                           22.9                     6   
3                            5.4                     4   
4                          102.3                    22   
...                          ...                   ...   
2015                         NaN                   502   
2016                         NaN                    24   
2017                         NaN                     9   
2018                         NaN                    20   
2019                         NaN                     6   

                    Urban_area_2013_label  Urban_area_type  \
0                   Central Auckland Zone  Main urban area   
1                         Wellington Zone  Main urban area   
2                           Hamilton Zone  Main urban area   
3                   Central Auckland Zone  Main urban area   
4                            Christchurch  Main urban area   
...                                   ...              ...   
2015  Rural (Incl.some Off Shore Islands)       Rural area   
2016                         Invercargill  Main urban area   
2017                             Tauranga  Main urban area   
2018                      Wellington Zone  Main urban area   
2019                        Hamilton Zone  Main urban area   

      Territorial_authority_area_2013_code  \
0                                       76   
1                    

In [75]:
data.groupby("Urban_area_2013_label").count()["Area_unit_2013_label"]

Urban_area_2013_label
Alexandra     1
Amberley      1
Arrowtown     1
Ashburton    11
Balclutha     1
             ..
Whangarei    29
Whitianga     1
Winton        1
Woodend       3
Woodville     1
Name: Area_unit_2013_label, Length: 150, dtype: int64

In [76]:
data.loc[(data["Population_mid_point_2015"] > 1) & (data["Victimisations per population"] == 0)]

Index  Area_unit_2013_code               Area_unit_2013_label  \
1729   1730               626100                Inlet-Milford Sound   
1730   1731               623900                    Inlet-Ligar Bay   
1731   1732               625800                Inlet-Otago Harbour   
1732   1733               619301  Inlets-Thames-Coromandel District   
1733   1734               612901                          Fiordland   
...     ...                  ...                                ...   
2015   2016               506653                          Riverhead   
2016   2017               610601                           Grasmere   
2017   2018               536513                     Bethlehem East   
2018   2019               574302                          Te Kainga   
2019   2020               527007                      Horsham Downs   

      Victimisations_calendar_year_2015  Population_mid_point_2015  \
1729                                  0                         10   
1730                                  0                         10   
1731                                  0                         10   
1732                                  0                         10   
1733                                  0                         10   
...                                 ...                        ...   
2015                                  0                       3510   
2016                                  0                       3590   
2017                                  0                       3590   
2018                                  0                       4020   
2019                                  0                       5440   

      Victimisations per population Rate_per_10000_population  \
1729                            0.0                       NaN   
1730                            0.0                       NaN   
1731                            0.0                       NaN   
1732                            0.0                       NaN   
1733                            0.0                       NaN   
...                             ...                       ...   
2015                            0.0                       NaN   
2016                            0.0                       NaN   
2017                            0.0                       NaN   
2018                            0.0                       NaN   
2019                            0.0                       NaN   

      Rate_ratio_NZ_average_rate  Urban_area_2013_code  \
1729                         NaN                   507   
1730                         NaN                   507   
1731                         NaN                   507   
1732                         NaN                   507   
1733                         NaN                   502   
...                          ...                   ...   
2015                         NaN                   502   
2016                         NaN                    24   
2017                         NaN                     9   
2018                         NaN                    20   
2019                         NaN                     6   

                    Urban_area_2013_label  Urban_area_type  \
1729    Inlet-in TA but not in Urban Area       Rural area   
1730    Inlet-in TA but not in Urban Area       Rural area   
1731    Inlet-in TA but not in Urban Area       Rural area   
1732    Inlet-in TA but not in Urban Area       Rural area   
1733  Rural (Incl.some Off Shore Islands)       Rural area   
...                                   ...              ...   
2015  Rural (Incl.some Off Shore Islands)       Rural area   
2016                         Invercargill  Main urban area   
2017                             Tauranga  Main urban area   
2018                      Wellington Zone  Main urban area   
2019                        Hamilton Zone  Main urban area   

      Territorial_authority_area_2013_code  \
1729                                    73 

In [77]:
data.isnull().sum()

Index                                      0
Area_unit_2013_code                        0
Area_unit_2013_label                       0
Victimisations_calendar_year_2015          0
Population_mid_point_2015                  0
Victimisations per population            116
Rate_per_10000_population                417
Rate_ratio_NZ_average_rate               417
Urban_area_2013_code                       0
Urban_area_2013_label                      0
Urban_area_type                            0
Territorial_authority_area_2013_code       0
Territorial_authority_area_2013_label      0
Region_2013_code                           0
Region_2013_label                          0
dtype: int64

In [85]:
data.loc[(data["Rate_per_10000_population"] != "NaN") & (data["Population_mid_point_2015"] > 5000)].sort_values("Rate_per_10000_population", ascending=True).head(10)

Index  Area_unit_2013_code Area_unit_2013_label  \
808    809               562200         Kelvin Grove   
968    969               501802    Opouteke-Tanekaha   
967    968               597730                Hinds   
887    888               528310               Bryant   
886    887               508411              Glendhu   
885    886               509400          Mt Victoria   
807    808               508520            Sunnynook   
690    691               527009           Huntington   
36      37               524200        Mangere South   
63      64               524822        Clendon South   

     Victimisations_calendar_year_2015  Population_mid_point_2015  \
808                                  7                       7290   
968                                  5                       5070   
967                                  5                       5030   
887                                  6                       6150   
886                                  6                       6030   
885                                  6                       5800   
807                                  7                       7220   
690                                  9                       8630   
36                                  81                       7980   
63                                  57                       5560   

     Victimisations per population Rate_per_10000_population  \
808                       0.096022                        10   
968                       0.098619                        10   
967                       0.099404                        10   
887                       0.097561                        10   
886                       0.099502                        10   
885                       0.103448                        10   
807                       0.096953                        10   
690                       0.104287                        10   
36                        1.015038                       102   
63                        1.025180                       103   

     Rate_ratio_NZ_average_rate  Urban_area_2013_code  \
808                         0.2                    16   
968                         0.2                   502   
967                         0.2                   502   
887                         0.2                     6   
886                         0.2                     2   
885                         0.2                     2   
807                         0.2                     2   
690                         0.2                     6   
36                          1.9                     5   
63                          2.0                     5   

                   Urban_area_2013_label  Urban_area_type  \
808                     Palmerston North  Main urban area   
968  Rural (Incl.some Off Shore Islands)       Rural area   
967  Rural (Incl.some Off Shore Islands)       Rural area   
887                        Hamilton Zone  Main urban area   
886               Northern Auckland Zone  Main urban area   
885               Northern Auckland Zone  Main urban area   
807               Northern Auckland Zone  Main urban area   
690                        Hamilton Zone  Main urban area   
36                Southern Auckland Zone  Main urban area   
63                Southern Auckland Zone  Main urban area   

     Territorial_authority_area_2013_code  \
808                                    40   
968                                     2   
967                                    63   
887                                    16   
886                                    76   
885                                    76   
807                                    76   
690                                    16   
36                                     76   
63                                     76   

    Territorial_authority_area_2013_label  Region_2013_code  \
808                 Palmerston North City                 8   
9

In [97]:
regions = data.groupby("Region_2013_label").sum()
regions

Index  Area_unit_2013_code  \
Region_2013_label                                       
Area Outside Region        31979             12115406   
Auckland Region           351263            228136920   
Bay of Plenty Region      116270             69921421   
Canterbury Region         263734            152971702   
Gisborne Region            18953             13134931   
Hawke's Bay Region         80181             46166145   
Manawatu-Wanganui Region  128256             72064146   
Marlborough Region         31022             15140741   
Nelson Region              31980             18146617   
Northland Region           96901             49951297   
Otago Region              156828             79941938   
Southland Region          101248             48378906   
Taranaki Region            75287             36602672   
Tasman Region              36562             17552636   
Waikato Region            214201            112175975   
Wellington Region         221263            121963800   
West Coast Region          85282             33421322   

                          Victimisations_calendar_year_2015  \
Region_2013_label                                             
Area Outside Region                                       0   
Auckland Region                                        8010   
Bay of Plenty Region                                   1751   
Canterbury Region                                      2942   
Gisborne Region                                         436   
Hawke's Bay Region                                     1068   
Manawatu-Wanganui Region                               1270   
Marlborough Region                                      209   
Nelson Region                                           357   
Northland Region                                        905   
Otago Region                                           1142   
Southland Region                                        381   
Taranaki Region                                         493   
Tasman Region                                           161   
Waikato Region                                         2330   
Wellington Region                                      2459   
West Coast Region                                       121   

                          Population_mid_point_2015  \
Region_2013_label                                     
Area Outside Region                             610   
Auckland Region                             1569890   
Bay of Plenty Region                         287130   
Canterbury Region                            586310   
Gisborne Region                               47370   
Hawke's Bay Region                           160010   
Manawatu-Wanganui Region                     234460   
Marlborough Region                            45340   
Nelson Region                                 49940   
Northland Region                             168320   
Otago Region                                 215030   
Southland Region                              97190   
Taranaki Region                              115760   
Tasman Region                                 49500   
Waikato Region                               439000   
Wellington Region                            496890   
West Coast Region                             32700   

                          Victimisations per population  \
Region_2013_label                                         
Area Outside Region                            0.000000   
Auckland Region                                     NaN   
Bay of Plenty Region                                NaN   
Canterbury Region                            170.935138   
Gisborne Region                               17.247905   
Hawke's Bay Region                            65.434814   
Manawatu-Wanganui Region                      87.073779   
Marlborough Region                            15.546369   
Nelson Region                                       NaN   
Northland Region                                  

In [98]:
regions.insert(4, "Rate_per_10000_population", regions["Victimisations_calendar_year_2015"] / regions["Population_mid_point_2015"] * 10000)
regions

Index  Area_unit_2013_code  \
Region_2013_label                                       
Area Outside Region        31979             12115406   
Auckland Region           351263            228136920   
Bay of Plenty Region      116270             69921421   
Canterbury Region         263734            152971702   
Gisborne Region            18953             13134931   
Hawke's Bay Region         80181             46166145   
Manawatu-Wanganui Region  128256             72064146   
Marlborough Region         31022             15140741   
Nelson Region              31980             18146617   
Northland Region           96901             49951297   
Otago Region              156828             79941938   
Southland Region          101248             48378906   
Taranaki Region            75287             36602672   
Tasman Region              36562             17552636   
Waikato Region            214201            112175975   
Wellington Region         221263            121963800   
West Coast Region          85282             33421322   

                          Victimisations_calendar_year_2015  \
Region_2013_label                                             
Area Outside Region                                       0   
Auckland Region                                        8010   
Bay of Plenty Region                                   1751   
Canterbury Region                                      2942   
Gisborne Region                                         436   
Hawke's Bay Region                                     1068   
Manawatu-Wanganui Region                               1270   
Marlborough Region                                      209   
Nelson Region                                           357   
Northland Region                                        905   
Otago Region                                           1142   
Southland Region                                        381   
Taranaki Region                                         493   
Tasman Region                                           161   
Waikato Region                                         2330   
Wellington Region                                      2459   
West Coast Region                                       121   

                          Population_mid_point_2015  \
Region_2013_label                                     
Area Outside Region                             610   
Auckland Region                             1569890   
Bay of Plenty Region                         287130   
Canterbury Region                            586310   
Gisborne Region                               47370   
Hawke's Bay Region                           160010   
Manawatu-Wanganui Region                     234460   
Marlborough Region                            45340   
Nelson Region                                 49940   
Northland Region                             168320   
Otago Region                                 215030   
Southland Region                              97190   
Taranaki Region                              115760   
Tasman Region                                 49500   
Waikato Region                               439000   
Wellington Region                            496890   
West Coast Region                             32700   

                          Rate_per_10000_population  \
Region_2013_label                                     
Area Outside Region                        0.000000   
Auckland Region                           51.022683   
Bay of Plenty Region                      60.982830   
Canterbury Region                         50.178233   
Gisborne Region                           92.041376   
Hawke's Bay Region                        66.745828   
Manawatu-Wanganui Region                  54.167022   
Marlborough Region                        46.096162   
Nelson Region                             71.485783   
Northland Region                          53.766635   
Otago Region                           

In [99]:
regions = regions.drop(columns="Victimisations per population")
regions

Index  Area_unit_2013_code  \
Region_2013_label                                       
Area Outside Region        31979             12115406   
Auckland Region           351263            228136920   
Bay of Plenty Region      116270             69921421   
Canterbury Region         263734            152971702   
Gisborne Region            18953             13134931   
Hawke's Bay Region         80181             46166145   
Manawatu-Wanganui Region  128256             72064146   
Marlborough Region         31022             15140741   
Nelson Region              31980             18146617   
Northland Region           96901             49951297   
Otago Region              156828             79941938   
Southland Region          101248             48378906   
Taranaki Region            75287             36602672   
Tasman Region              36562             17552636   
Waikato Region            214201            112175975   
Wellington Region         221263            121963800   
West Coast Region          85282             33421322   

                          Victimisations_calendar_year_2015  \
Region_2013_label                                             
Area Outside Region                                       0   
Auckland Region                                        8010   
Bay of Plenty Region                                   1751   
Canterbury Region                                      2942   
Gisborne Region                                         436   
Hawke's Bay Region                                     1068   
Manawatu-Wanganui Region                               1270   
Marlborough Region                                      209   
Nelson Region                                           357   
Northland Region                                        905   
Otago Region                                           1142   
Southland Region                                        381   
Taranaki Region                                         493   
Tasman Region                                           161   
Waikato Region                                         2330   
Wellington Region                                      2459   
West Coast Region                                       121   

                          Population_mid_point_2015  \
Region_2013_label                                     
Area Outside Region                             610   
Auckland Region                             1569890   
Bay of Plenty Region                         287130   
Canterbury Region                            586310   
Gisborne Region                               47370   
Hawke's Bay Region                           160010   
Manawatu-Wanganui Region                     234460   
Marlborough Region                            45340   
Nelson Region                                 49940   
Northland Region                             168320   
Otago Region                                 215030   
Southland Region                              97190   
Taranaki Region                              115760   
Tasman Region                                 49500   
Waikato Region                               439000   
Wellington Region                            496890   
West Coast Region                             32700   

                          Rate_per_10000_population  \
Region_2013_label                                     
Area Outside Region                        0.000000   
Auckland Region                           51.022683   
Bay of Plenty Region                      60.982830   
Canterbury Region                         50.178233   
Gisborne Region                           92.041376   
Hawke's Bay Region                        66.745828   
Manawatu-Wanganui Region                  54.167022   
Marlborough Region                        46.096162   
Nelson Region                             71.485783   
Northland Region                          53.766635   
Otago Region                           

In [100]:
regions.insert(4, "Victimisations per population", regions['Victimisations_calendar_year_2015'] / regions['Population_mid_point_2015'] * 100)
regions

Index  Area_unit_2013_code  \
Region_2013_label                                       
Area Outside Region        31979             12115406   
Auckland Region           351263            228136920   
Bay of Plenty Region      116270             69921421   
Canterbury Region         263734            152971702   
Gisborne Region            18953             13134931   
Hawke's Bay Region         80181             46166145   
Manawatu-Wanganui Region  128256             72064146   
Marlborough Region         31022             15140741   
Nelson Region              31980             18146617   
Northland Region           96901             49951297   
Otago Region              156828             79941938   
Southland Region          101248             48378906   
Taranaki Region            75287             36602672   
Tasman Region              36562             17552636   
Waikato Region            214201            112175975   
Wellington Region         221263            121963800   
West Coast Region          85282             33421322   

                          Victimisations_calendar_year_2015  \
Region_2013_label                                             
Area Outside Region                                       0   
Auckland Region                                        8010   
Bay of Plenty Region                                   1751   
Canterbury Region                                      2942   
Gisborne Region                                         436   
Hawke's Bay Region                                     1068   
Manawatu-Wanganui Region                               1270   
Marlborough Region                                      209   
Nelson Region                                           357   
Northland Region                                        905   
Otago Region                                           1142   
Southland Region                                        381   
Taranaki Region                                         493   
Tasman Region                                           161   
Waikato Region                                         2330   
Wellington Region                                      2459   
West Coast Region                                       121   

                          Population_mid_point_2015  \
Region_2013_label                                     
Area Outside Region                             610   
Auckland Region                             1569890   
Bay of Plenty Region                         287130   
Canterbury Region                            586310   
Gisborne Region                               47370   
Hawke's Bay Region                           160010   
Manawatu-Wanganui Region                     234460   
Marlborough Region                            45340   
Nelson Region                                 49940   
Northland Region                             168320   
Otago Region                                 215030   
Southland Region                              97190   
Taranaki Region                              115760   
Tasman Region                                 49500   
Waikato Region                               439000   
Wellington Region                            496890   
West Coast Region                             32700   

                          Victimisations per population  \
Region_2013_label                                         
Area Outside Region                            0.000000   
Auckland Region                                0.510227   
Bay of Plenty Region                           0.609828   
Canterbury Region                              0.501782   
Gisborne Region                                0.920414   
Hawke's Bay Region                             0.667458   
Manawatu-Wanganui Region                       0.541670   
Marlborough Region                             0.460962   
Nelson Region                                  0.714858   
Northland Region                               0.5